// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const areFriends = `-- name: AreFriends :one
SELECT EXISTS(
    SELECT 1 FROM friendships WHERE user_id = $1 AND friend_id = $2
) AS are_friends
`

type AreFriendsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, areFriends, arg.UserID, arg.FriendID)
	var are_friends bool
	err := row.Scan(&are_friends)
	return are_friends, err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships (user_id, friend_id) VALUES ($1, $2), ($2, $1)
ON CONFLICT DO NOTHING
`

type CreateFriendshipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, createFriendship, arg.UserID, arg.FriendID)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
`

type DeleteFriendshipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FriendID uuid.UUID `json:"friend_id"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const getFriendRequest = `-- name: GetFriendRequest :one
SELECT id, from_id, to_id, status, created_at, updated_at FROM friend_requests WHERE id = $1
`

func (q *Queries) GetFriendRequest(ctx context.Context, id uuid.UUID) (FriendRequest, error) {
	row := q.db.QueryRowContext(ctx, getFriendRequest, id)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriends = `-- name: GetFriends :many
SELECT u.id, u.phone, u.created_at
FROM friendships f
JOIN users u ON u.id = f.friend_id
WHERE f.user_id = $1
ORDER BY u.phone
`

func (q *Queries) GetFriends(ctx context.Context, userID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Phone, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendsWithStatus = `-- name: GetFriendsWithStatus :many
SELECT
    u.id,
    u.phone,
    us.id AS status_id,
    us.expires_at,
    us.activities,
    us.district
FROM friendships f
JOIN users u ON u.id = f.friend_id
LEFT JOIN user_statuses us ON us.user_id = u.id AND us.expires_at > now()
WHERE f.user_id = $1
ORDER BY (us.id IS NOT NULL) DESC, u.phone
`

type GetFriendsWithStatusRow struct {
	ID         uuid.UUID      `json:"id"`
	Phone      string         `json:"phone"`
	StatusID   uuid.NullUUID  `json:"status_id"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
	Activities []string       `json:"activities"`
	District   sql.NullString `json:"district"`
}

func (q *Queries) GetFriendsWithStatus(ctx context.Context, userID uuid.UUID) ([]GetFriendsWithStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendsWithStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsWithStatusRow
	for rows.Next() {
		var i GetFriendsWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.StatusID,
			&i.ExpiresAt,
			pq.Array(&i.Activities),
			&i.District,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingRequestsForUser = `-- name: GetPendingRequestsForUser :many
SELECT fr.id, fr.from_id, fr.to_id, fr.status, fr.created_at, fr.updated_at, u.phone as from_phone
FROM friend_requests fr
JOIN users u ON u.id = fr.from_id
WHERE fr.to_id = $1 AND fr.status = 'pending'
ORDER BY fr.created_at DESC
`

type GetPendingRequestsForUserRow struct {
	ID        uuid.UUID `json:"id"`
	FromID    uuid.UUID `json:"from_id"`
	ToID      uuid.UUID `json:"to_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	FromPhone string    `json:"from_phone"`
}

func (q *Queries) GetPendingRequestsForUser(ctx context.Context, toID uuid.UUID) ([]GetPendingRequestsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRequestsForUser, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingRequestsForUserRow
	for rows.Next() {
		var i GetPendingRequestsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.ToID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO friend_requests (from_id, to_id)
VALUES ($1, $2)
ON CONFLICT (from_id, to_id) DO UPDATE SET status = 'pending', updated_at = now()
RETURNING id, from_id, to_id, status, created_at, updated_at
`

type SendFriendRequestParams struct {
	FromID uuid.UUID `json:"from_id"`
	ToID   uuid.UUID `json:"to_id"`
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRowContext(ctx, sendFriendRequest, arg.FromID, arg.ToID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFriendRequestStatus = `-- name: UpdateFriendRequestStatus :one
UPDATE friend_requests SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, from_id, to_id, status, created_at, updated_at
`

type UpdateFriendRequestStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateFriendRequestStatus(ctx context.Context, arg UpdateFriendRequestStatusParams) (FriendRequest, error) {
	row := q.db.QueryRowContext(ctx, updateFriendRequestStatus, arg.ID, arg.Status)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
