// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countPingsFromUser = `-- name: CountPingsFromUser :one
SELECT COUNT(*) FROM pings
WHERE from_id = $1 AND created_at > now() - interval '1 hour'
`

func (q *Queries) CountPingsFromUser(ctx context.Context, fromID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPingsFromUser, fromID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (from_id, to_id, message, activity, expires_at)
VALUES ($1, $2, $3, $4, now() + interval '24 hours')
RETURNING id, from_id, to_id, message, status, activity, expires_at, created_at, updated_at
`

type CreateInvitationParams struct {
	FromID   uuid.UUID      `json:"from_id"`
	ToID     uuid.UUID      `json:"to_id"`
	Message  sql.NullString `json:"message"`
	Activity sql.NullString `json:"activity"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.FromID,
		arg.ToID,
		arg.Message,
		arg.Activity,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Message,
		&i.Status,
		&i.Activity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPing = `-- name: CreatePing :one
INSERT INTO pings (from_id, to_id) VALUES ($1, $2) RETURNING id, from_id, to_id, created_at
`

type CreatePingParams struct {
	FromID uuid.UUID `json:"from_id"`
	ToID   uuid.UUID `json:"to_id"`
}

func (q *Queries) CreatePing(ctx context.Context, arg CreatePingParams) (Ping, error) {
	row := q.db.QueryRowContext(ctx, createPing, arg.FromID, arg.ToID)
	var i Ping
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCallMeFlag = `-- name: DeleteCallMeFlag :exec
DELETE FROM call_me_flags WHERE user_id = $1
`

func (q *Queries) DeleteCallMeFlag(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCallMeFlag, userID)
	return err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceToken, token)
	return err
}

const getActiveCallMeFlag = `-- name: GetActiveCallMeFlag :one
SELECT id, user_id, enabled_at, expires_at FROM call_me_flags WHERE user_id = $1 AND expires_at > now()
`

func (q *Queries) GetActiveCallMeFlag(ctx context.Context, userID uuid.UUID) (CallMeFlag, error) {
	row := q.db.QueryRowContext(ctx, getActiveCallMeFlag, userID)
	var i CallMeFlag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EnabledAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getDeviceTokensForUser = `-- name: GetDeviceTokensForUser :many
SELECT token FROM device_tokens WHERE user_id = $1 AND platform = 'ios'
`

func (q *Queries) GetDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, from_id, to_id, message, status, activity, expires_at, created_at, updated_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Message,
		&i.Status,
		&i.Activity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingInvitationsForUser = `-- name: GetPendingInvitationsForUser :many
SELECT i.id, i.from_id, i.to_id, i.message, i.status, i.activity, i.expires_at, i.created_at, i.updated_at, u.phone AS from_phone
FROM invitations i
JOIN users u ON u.id = i.from_id
WHERE i.to_id = $1 AND i.status = 'pending' AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type GetPendingInvitationsForUserRow struct {
	ID        uuid.UUID      `json:"id"`
	FromID    uuid.UUID      `json:"from_id"`
	ToID      uuid.UUID      `json:"to_id"`
	Message   sql.NullString `json:"message"`
	Status    string         `json:"status"`
	Activity  sql.NullString `json:"activity"`
	ExpiresAt time.Time      `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	FromPhone string         `json:"from_phone"`
}

func (q *Queries) GetPendingInvitationsForUser(ctx context.Context, toID uuid.UUID) ([]GetPendingInvitationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInvitationsForUser, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingInvitationsForUserRow
	for rows.Next() {
		var i GetPendingInvitationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.ToID,
			&i.Message,
			&i.Status,
			&i.Activity,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentInvitations = `-- name: GetSentInvitations :many
SELECT i.id, i.from_id, i.to_id, i.message, i.status, i.activity, i.expires_at, i.created_at, i.updated_at, u.phone AS to_phone
FROM invitations i
JOIN users u ON u.id = i.to_id
WHERE i.from_id = $1 AND i.status = 'pending' AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type GetSentInvitationsRow struct {
	ID        uuid.UUID      `json:"id"`
	FromID    uuid.UUID      `json:"from_id"`
	ToID      uuid.UUID      `json:"to_id"`
	Message   sql.NullString `json:"message"`
	Status    string         `json:"status"`
	Activity  sql.NullString `json:"activity"`
	ExpiresAt time.Time      `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	ToPhone   string         `json:"to_phone"`
}

func (q *Queries) GetSentInvitations(ctx context.Context, fromID uuid.UUID) ([]GetSentInvitationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSentInvitations, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSentInvitationsRow
	for rows.Next() {
		var i GetSentInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.ToID,
			&i.Message,
			&i.Status,
			&i.Activity,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ToPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE invitations SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, from_id, to_id, message, status, activity, expires_at, created_at, updated_at
`

type UpdateInvitationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, updateInvitationStatus, arg.ID, arg.Status)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Message,
		&i.Status,
		&i.Activity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCallMeFlag = `-- name: UpsertCallMeFlag :exec
INSERT INTO call_me_flags (user_id, expires_at)
VALUES ($1, now() + interval '4 hours')
ON CONFLICT (user_id) DO UPDATE SET enabled_at = now(), expires_at = now() + interval '4 hours'
`

func (q *Queries) UpsertCallMeFlag(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upsertCallMeFlag, userID)
	return err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE SET user_id = $1
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	return err
}
