// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type PhoneVerification struct {
	ID        uuid.UUID `json:"id"`
	Phone     string    `json:"phone"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
}

type UserStatus struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	ExpiresAt  time.Time       `json:"expires_at"`
	Activities []string        `json:"activities"`
	Lat        sql.NullFloat64 `json:"lat"`
	Lon        sql.NullFloat64 `json:"lon"`
	District   sql.NullString  `json:"district"`
	CreatedAt  time.Time       `json:"created_at"`
}
