// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CreateStatus(ctx context.Context, arg CreateStatusParams) (UserStatus, error)
	CreateUser(ctx context.Context, phone string) (User, error)
	CreateVerification(ctx context.Context, arg CreateVerificationParams) (PhoneVerification, error)
	DeleteActiveStatuses(ctx context.Context, userID uuid.UUID) error
	DeleteExpiredOlderThan(ctx context.Context, expiresAt time.Time) error
	DeleteUserStatus(ctx context.Context, userID uuid.UUID) error
	GetActiveStatus(ctx context.Context, userID uuid.UUID) (UserStatus, error)
	GetActiveVerification(ctx context.Context, phone string) (PhoneVerification, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	MarkVerificationUsed(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
