// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createStatus = `-- name: CreateStatus :one
INSERT INTO user_statuses (user_id, expires_at, activities, lat, lon, district)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, expires_at, activities, lat, lon, district, created_at
`

type CreateStatusParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	ExpiresAt  time.Time       `json:"expires_at"`
	Activities []string        `json:"activities"`
	Lat        sql.NullFloat64 `json:"lat"`
	Lon        sql.NullFloat64 `json:"lon"`
	District   sql.NullString  `json:"district"`
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (UserStatus, error) {
	row := q.db.QueryRowContext(ctx, createStatus,
		arg.UserID,
		arg.ExpiresAt,
		pq.Array(arg.Activities),
		arg.Lat,
		arg.Lon,
		arg.District,
	)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		pq.Array(&i.Activities),
		&i.Lat,
		&i.Lon,
		&i.District,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActiveStatuses = `-- name: DeleteActiveStatuses :exec
DELETE FROM user_statuses
WHERE user_id = $1
  AND expires_at > now()
`

func (q *Queries) DeleteActiveStatuses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteActiveStatuses, userID)
	return err
}

const deleteExpiredOlderThan = `-- name: DeleteExpiredOlderThan :exec
DELETE FROM user_statuses WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredOlderThan(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOlderThan, expiresAt)
	return err
}

const deleteUserStatus = `-- name: DeleteUserStatus :exec
DELETE FROM user_statuses WHERE user_id = $1
`

func (q *Queries) DeleteUserStatus(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserStatus, userID)
	return err
}

const getActiveStatus = `-- name: GetActiveStatus :one
SELECT id, user_id, expires_at, activities, lat, lon, district, created_at FROM user_statuses
WHERE user_id = $1
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveStatus(ctx context.Context, userID uuid.UUID) (UserStatus, error) {
	row := q.db.QueryRowContext(ctx, getActiveStatus, userID)
	var i UserStatus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		pq.Array(&i.Activities),
		&i.Lat,
		&i.Lon,
		&i.District,
		&i.CreatedAt,
	)
	return i, err
}
