// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerification = `-- name: CreateVerification :one
INSERT INTO phone_verifications (phone, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, phone, code, expires_at, used, created_at
`

type CreateVerificationParams struct {
	Phone     string    `json:"phone"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) (PhoneVerification, error) {
	row := q.db.QueryRowContext(ctx, createVerification, arg.Phone, arg.Code, arg.ExpiresAt)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveVerification = `-- name: GetActiveVerification :one
SELECT id, phone, code, expires_at, used, created_at FROM phone_verifications
WHERE phone = $1
  AND used = false
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveVerification(ctx context.Context, phone string) (PhoneVerification, error) {
	row := q.db.QueryRowContext(ctx, getActiveVerification, phone)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markVerificationUsed = `-- name: MarkVerificationUsed :exec
UPDATE phone_verifications SET used = true WHERE id = $1
`

func (q *Queries) MarkVerificationUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markVerificationUsed, id)
	return err
}
